baseURL: "https://bubblegits.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: 张珙的博客
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: 东读西读
                  url: post/reading
                  weight: 1
                - name: 胡思乱想
                  url: post/essay
                  weight: 2
                - name: 奇技淫巧
                  url: post/work
                  weight: 3
                - name: 朝花夕拾
                  url: post/autobiography
                  weight: 4
                - name: 搜索
                  url: search/
                  weight: 5
                - name: 标签
                  url: tags/
                  weight: 6

outputs:
    home:
        - HTML
        - RSS
        - JSON

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
